### ISSUE TITLE
add user

### ISSUE THREAD

**Issue by saadamir3180** [HuzaifaRizwan1231/RestaurantMenuApp#1]
## SignUp Issue

Upon completing the account creation process, the application crashes. The application becomes unavailable for the specific IP address. While it appears that the user is registered, there seems to be an issue with how the authentication data is being managed or processed.

Kindly investigate and address this issue.

**Comment by saadamir3180** [comment]
## Issue not resoved?

**Comment by HuzaifaRizwan1231** [comment]
Thanks for pointing out this issue. I have looked into it and fixed this issue. Now, there should be no problems in signing up. 

If the issue still persists on a specific device, try clearing the localStorage. 

Here is an article to help you out: 

[https://support.conquer.io/hc/en-us/articles/5821475923988-How-to-clear-local-storage-in-Chrome]

Let me know if you have any other issue.

**Comment by saadamir3180** [comment]
## Ohh Thanks! 
Finally i Can Sign in and and order my Delicious 😋 food on the Spot.
